// generated by Fast Light User Interface Designer (fluid) version 1.0402

#include "pcb_window.h"
#include "cb_pcb_window.h"
#include "fl_mouse_box.h"

Fl_Menu_Item pcb_window::menu_mode_sel[] = {
 {"Net", 0,  0, 0, 8, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Part", 0,  0, 0, 8, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

pcb_window::pcb_window() {
  { window = new Fl_Window(1277, 540, "PCB Annot");
    window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(1000, 387, 275, 113, "netlist / pinlist");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { sel_part = new Fl_Choice(1085, 408, 180, 22, "part");
        sel_part->down_box(FL_BORDER_BOX);
        sel_part->callback((Fl_Callback*)pcb_infos_window_callback, (void*)(this));
      } // Fl_Choice* sel_part
      { sel_net = new Fl_Choice(1085, 443, 180, 22, "net");
        sel_net->down_box(FL_BORDER_BOX);
        sel_net->callback((Fl_Callback*)pcb_infos_window_callback, (void*)(this));
      } // Fl_Choice* sel_net
      { zp = new Fl_Button(1010, 473, 26, 20, "+");
        zp->callback((Fl_Callback*)bt_zp_callback);
      } // Fl_Button* zp
      { zm = new Fl_Button(1036, 473, 28, 20, "-");
        zm->callback((Fl_Callback*)bt_zm_callback);
      } // Fl_Button* zm
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(1000, 2, 270, 168, "Status");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { x_pos = new Fl_Output(1005, 17, 265, 15);
        x_pos->labelsize(10);
        x_pos->textsize(10);
      } // Fl_Output* x_pos
      { y_pos = new Fl_Output(1005, 33, 265, 15);
        y_pos->labelsize(10);
        y_pos->textsize(10);
      } // Fl_Output* y_pos
      { global_status = new Fl_Output(1005, 49, 265, 16);
        global_status->labelsize(10);
        global_status->textsize(10);
      } // Fl_Output* global_status
      { object_txt = new Fl_Text_Display(1005, 68, 260, 96);
        object_txt->labelsize(10);
        object_txt->textsize(10);
        object_txt->user_data((void*)(this));
      } // Fl_Text_Display* object_txt
      o->end();
    } // Fl_Group* o
    { pcb_disp = new Fl_Group(0, 1, 995, 539, "Edit Area");
      pcb_disp->box(FL_ENGRAVED_FRAME);
      pcb_disp->labeltype(FL_EMBOSSED_LABEL);
      pcb_disp->labelsize(12);
      pcb_disp->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      pcb_disp->end();
      Fl_Group::current()->resizable(pcb_disp);
    } // Fl_Group* pcb_disp
    { Fl_Group* o = new Fl_Group(1005, 505, 265, 35, "Project");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { Fl_Button* o = new Fl_Button(1175, 510, 80, 25, "Save");
        o->callback((Fl_Callback*)pcb_save, (void*)(this));
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(1000, 170, 270, 209, "Edit mode");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(10);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { mode_sel = new Fl_Choice(1092, 189, 155, 28, "edit mode:");
        mode_sel->down_box(FL_BORDER_BOX);
        mode_sel->menu(menu_mode_sel);
      } // Fl_Choice* mode_sel
      { next_part = new Fl_Button(1003, 225, 74, 22, "Next Part");
        next_part->callback((Fl_Callback*)bt_next_part_callback);
      } // Fl_Button* next_part
      { next_net = new Fl_Button(1003, 251, 74, 22, "Next Net");
        next_net->callback((Fl_Callback*)bt_next_net_callback);
      } // Fl_Button* next_net
      { clear_pin = new Fl_Button(1077, 225, 71, 22, "Clear pin");
        clear_pin->callback((Fl_Callback*)bt_clear_pin_callback);
      } // Fl_Button* clear_pin
      { clear_net = new Fl_Button(1077, 251, 71, 22, "Clear net");
        clear_net->callback((Fl_Callback*)bt_clear_net_callback);
      } // Fl_Button* clear_net
      { curpin = new Fl_Output(1199, 225, 66, 22, "cupin");
      } // Fl_Output* curpin
      { curnet = new Fl_Output(1199, 251, 66, 22, "curnet");
      } // Fl_Output* curnet
      { slide_l00 = new Fl_Slider(1003, 306, 22, 48, "L00");
        slide_l00->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l00
      { slide_l01 = new Fl_Slider(1028, 306, 22, 48, "L01");
        slide_l01->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l01
      { slide_l02 = new Fl_Slider(1053, 306, 22, 48, "L02");
        slide_l02->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l02
      { slide_l03 = new Fl_Slider(1078, 306, 22, 48, "L03");
        slide_l03->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l03
      { slide_l04 = new Fl_Slider(1103, 306, 22, 48, "L04");
        slide_l04->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l04
      { slide_l05 = new Fl_Slider(1128, 306, 22, 48, "L05");
        slide_l05->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l05
      { slide_l06 = new Fl_Slider(1153, 306, 22, 48, "L06");
        slide_l06->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l06
      { slide_l07 = new Fl_Slider(1178, 306, 22, 48, "L07");
        slide_l07->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_l07
      { slide_pins = new Fl_Slider(1207, 306, 22, 48, "Pins");
        slide_pins->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_pins
      { slide_nets = new Fl_Slider(1238, 306, 22, 48, "Nets");
        slide_nets->callback((Fl_Callback*)slide_changed);
      } // Fl_Slider* slide_nets
      o->end();
    } // Fl_Group* o

	Fl_Mouse_Box *m = new Fl_Mouse_Box(pcb_disp->x(), pcb_disp->y(),pcb_disp->w(), pcb_disp->h(), 0);
	m->callback(mouse_di_cb);

    window->end();
  } // Fl_Window* window
}
