// generated by Fast Light User Interface Designer (fluid) version 1.0402

#ifndef pcb_window_h
#define pcb_window_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>

#include <FL/Fl_Output.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
extern void pcb_save(Fl_Button*, void*);
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Slider.H>

class pcb_window {
public:
  pcb_window();
  Fl_Window *window;
  Fl_Choice *sel_part;
  Fl_Choice *sel_net;
  Fl_Button *zp;
  Fl_Button *zm;
  Fl_Output *x_pos;
  Fl_Output *y_pos;
  Fl_Output *global_status;
  Fl_Text_Display *object_txt;
  Fl_Group *pcb_disp;
  Fl_Choice *mode_sel;
  static Fl_Menu_Item menu_mode_sel[];
  Fl_Button *next_part;
  Fl_Button *next_net;
  Fl_Button *clear_pin;
  Fl_Button *clear_net;
  Fl_Output *curpin;
  Fl_Output *curnet;
  Fl_Slider *slide_l00;
  Fl_Slider *slide_l01;
  Fl_Slider *slide_l02;
  Fl_Slider *slide_l03;
  Fl_Slider *slide_l04;
  Fl_Slider *slide_l05;
  Fl_Slider *slide_l06;
  Fl_Slider *slide_l07;
  Fl_Slider *slide_pins;
  Fl_Slider *slide_nets;
  
  Fl_Text_Buffer* buf;

};
#endif
